replicaCount: 2

image:
  repository: 363685691972.dkr.ecr.eu-west-1.amazonaws.com/echo-server
  tag: "0.1.0"
  pullPolicy: IfNotPresent

service:
  port: 5678

ingress:
  host: echo-server.sandbox.k8s.putit.io
  entryPoints:
    - web
