apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Chart.Name }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.ingress.host }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: Host(`{{ .Values.ingress.host }}`)
      kind: Rule
      services:
        - name: {{ .Chart.Name }}
          port: {{ .Values.service.port }}
