replicaCount: 2

image:
  repository: 363685691972.dkr.ecr.eu-west-1.amazonaws.com/to-the-sky
  tag: "3db6b06"
  pullPolicy: IfNotPresent

service:
  port: 5789

ingress:
  host: to-the-sky.sandbox.k8s.putit.io
  target: traefik-pub-k8s.sandbox.k8s.putit.io

env:
  PORT: 5789
  DATABASE_HOST: "commonprefix-sandbox.clbkqrpgcjyt.eu-west-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "commonprefix"
  DATABASE_USERNAME: "commonprefix" 
  DATABASE_PASSWORD: "HYiM8F?c:!EatvJUBb8F|*>rI7*h"
