replicaCount: 2

image:
  repository: 363685691972.dkr.ecr.eu-west-1.amazonaws.com/echo-server
  tag: "3db6b06"
  pullPolicy: IfNotPresent

service:
  port: 5789

ingress:
  host: to-the-sky.sandbox.k8s.putit.io
  target: traefik-pub-k8s.sandbox.k8s.putit.io

env:
  PORT: 5789
  DATABASE_HOST: "example.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "commonprefix-sandbox"
  DATABASE_USERNAME: "commonprefix-sandbox" 
  DATABASE_PASSWORD: 'DB_54321'
